name: Docker Build

on:
  push:
    branches:
      - experimental

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Build & Docker Push
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'experimental'
      - name: Docker Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eedu/userms
          tags: experimental
